on:
  pull_request:

jobs:
  check-membership:
    runs-on: ubuntu-latest
    steps:
      - name: check membership
        env: 
          USERNAME: ${{ github.event.pull_request.user.login }}
          TOKEN: ${{ secrets.MEMBERSHIP_TOKEN }}
          ORG: test-organization-wengonn
        run: |
          echo "Verifying user's organization..."
          response=$(curl -s -L \
              -w "%{http_code}" \
              -o /dev/null -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/orgs/$ORG/memberships/$USERNAME")

          echo $response
          
          if [ $response != "200" ]; then
              echo "User is not a member of $ORG organization."
              exit 1
          else
              echo "User is a member of $ORG organization."
          fi
      
